//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ogama.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentFileList {
            get {
                return ((string)(this["RecentFileList"]));
            }
            set {
                this["RecentFileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point AOIModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["AOIModuleLocation"]));
            }
            set {
                this["AOIModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal NumberOfRecentFiles {
            get {
                return ((decimal)(this["NumberOfRecentFiles"]));
            }
            set {
                this["NumberOfRecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1x")]
        public string ReplaySpeed {
            get {
                return ((string)(this["ReplaySpeed"]));
            }
            set {
                this["ReplaySpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal MaxPointsPolyline {
            get {
                return ((decimal)(this["MaxPointsPolyline"]));
            }
            set {
                this["MaxPointsPolyline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal MaxNumberFixations {
            get {
                return ((decimal)(this["MaxNumberFixations"]));
            }
            set {
                this["MaxNumberFixations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeModeCursor {
            get {
                return ((bool)(this["GazeModeCursor"]));
            }
            set {
                this["GazeModeCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeModePath {
            get {
                return ((bool)(this["GazeModePath"]));
            }
            set {
                this["GazeModePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MouseModeCursor {
            get {
                return ((bool)(this["MouseModeCursor"]));
            }
            set {
                this["MouseModeCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MouseModePath {
            get {
                return ((bool)(this["MouseModePath"]));
            }
            set {
                this["MouseModePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GazeModeFixations {
            get {
                return ((bool)(this["GazeModeFixations"]));
            }
            set {
                this["GazeModeFixations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GazeModeFixCon {
            get {
                return ((bool)(this["GazeModeFixCon"]));
            }
            set {
                this["GazeModeFixCon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeModeSpotlight {
            get {
                return ((bool)(this["GazeModeSpotlight"]));
            }
            set {
                this["GazeModeSpotlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GazeModeCutPath {
            get {
                return ((bool)(this["GazeModeCutPath"]));
            }
            set {
                this["GazeModeCutPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeModeBlinks {
            get {
                return ((bool)(this["GazeModeBlinks"]));
            }
            set {
                this["GazeModeBlinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseModeFixations {
            get {
                return ((bool)(this["MouseModeFixations"]));
            }
            set {
                this["MouseModeFixations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseModeFixCon {
            get {
                return ((bool)(this["MouseModeFixCon"]));
            }
            set {
                this["MouseModeFixCon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseModeSpotlight {
            get {
                return ((bool)(this["MouseModeSpotlight"]));
            }
            set {
                this["MouseModeSpotlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseModeCutPath {
            get {
                return ((bool)(this["MouseModeCutPath"]));
            }
            set {
                this["MouseModeCutPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Circle")]
        public string GazeCursorType {
            get {
                return ((string)(this["GazeCursorType"]));
            }
            set {
                this["GazeCursorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GazeCursorColor {
            get {
                return ((global::System.Drawing.Color)(this["GazeCursorColor"]));
            }
            set {
                this["GazeCursorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle GazeCursorStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["GazeCursorStyle"]));
            }
            set {
                this["GazeCursorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float GazeCursorWidth {
            get {
                return ((float)(this["GazeCursorWidth"]));
            }
            set {
                this["GazeCursorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle GazePathStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["GazePathStyle"]));
            }
            set {
                this["GazePathStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GazePathColor {
            get {
                return ((global::System.Drawing.Color)(this["GazePathColor"]));
            }
            set {
                this["GazePathColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float GazePathWidth {
            get {
                return ((float)(this["GazePathWidth"]));
            }
            set {
                this["GazePathWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color GazeFixationsPenColor {
            get {
                return ((global::System.Drawing.Color)(this["GazeFixationsPenColor"]));
            }
            set {
                this["GazeFixationsPenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle GazeFixationsPenStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["GazeFixationsPenStyle"]));
            }
            set {
                this["GazeFixationsPenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float GazeFixationsPenWidth {
            get {
                return ((float)(this["GazeFixationsPenWidth"]));
            }
            set {
                this["GazeFixationsPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color GazeFixationConnectionsPenColor {
            get {
                return ((global::System.Drawing.Color)(this["GazeFixationConnectionsPenColor"]));
            }
            set {
                this["GazeFixationConnectionsPenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle GazeFixationConnectionsPenStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["GazeFixationConnectionsPenStyle"]));
            }
            set {
                this["GazeFixationConnectionsPenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float GazeFixationConnectionsPenWidth {
            get {
                return ((float)(this["GazeFixationConnectionsPenWidth"]));
            }
            set {
                this["GazeFixationConnectionsPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color MouseCursorColor {
            get {
                return ((global::System.Drawing.Color)(this["MouseCursorColor"]));
            }
            set {
                this["MouseCursorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle MouseCursorStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["MouseCursorStyle"]));
            }
            set {
                this["MouseCursorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float MouseCursorWidth {
            get {
                return ((float)(this["MouseCursorWidth"]));
            }
            set {
                this["MouseCursorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumBlue")]
        public global::System.Drawing.Color MousePathColor {
            get {
                return ((global::System.Drawing.Color)(this["MousePathColor"]));
            }
            set {
                this["MousePathColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle MousePathStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["MousePathStyle"]));
            }
            set {
                this["MousePathStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float MousePathWidth {
            get {
                return ((float)(this["MousePathWidth"]));
            }
            set {
                this["MousePathWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color MouseFixationsPenColor {
            get {
                return ((global::System.Drawing.Color)(this["MouseFixationsPenColor"]));
            }
            set {
                this["MouseFixationsPenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle MouseFixationsPenStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["MouseFixationsPenStyle"]));
            }
            set {
                this["MouseFixationsPenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float MouseFixationsPenWidth {
            get {
                return ((float)(this["MouseFixationsPenWidth"]));
            }
            set {
                this["MouseFixationsPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumBlue")]
        public global::System.Drawing.Color MouseFixationConnectionsPenColor {
            get {
                return ((global::System.Drawing.Color)(this["MouseFixationConnectionsPenColor"]));
            }
            set {
                this["MouseFixationConnectionsPenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle MouseFixationConnectionsPenStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["MouseFixationConnectionsPenStyle"]));
            }
            set {
                this["MouseFixationConnectionsPenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float MouseFixationConnectionsPenWidth {
            get {
                return ((float)(this["MouseFixationConnectionsPenWidth"]));
            }
            set {
                this["MouseFixationConnectionsPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GazeNoDataColor {
            get {
                return ((global::System.Drawing.Color)(this["GazeNoDataColor"]));
            }
            set {
                this["GazeNoDataColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dot")]
        public global::System.Drawing.Drawing2D.DashStyle GazeNoDataStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["GazeNoDataStyle"]));
            }
            set {
                this["GazeNoDataStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float GazeNoDataWidth {
            get {
                return ((float)(this["GazeNoDataWidth"]));
            }
            set {
                this["GazeNoDataWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public decimal GazeCursorSize {
            get {
                return ((decimal)(this["GazeCursorSize"]));
            }
            set {
                this["GazeCursorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public decimal MouseCursorSize {
            get {
                return ((decimal)(this["MouseCursorSize"]));
            }
            set {
                this["MouseCursorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arrow")]
        public string MouseCursorType {
            get {
                return ((string)(this["MouseCursorType"]));
            }
            set {
                this["MouseCursorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color AOISearchRectColor {
            get {
                return ((global::System.Drawing.Color)(this["AOISearchRectColor"]));
            }
            set {
                this["AOISearchRectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle AOISearchRectStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["AOISearchRectStyle"]));
            }
            set {
                this["AOISearchRectStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float AOISearchRectWidth {
            get {
                return ((float)(this["AOISearchRectWidth"]));
            }
            set {
                this["AOISearchRectWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color AOITargetColor {
            get {
                return ((global::System.Drawing.Color)(this["AOITargetColor"]));
            }
            set {
                this["AOITargetColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle AOITargetStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["AOITargetStyle"]));
            }
            set {
                this["AOITargetStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float AOITargetWidth {
            get {
                return ((float)(this["AOITargetWidth"]));
            }
            set {
                this["AOITargetWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color AOIStandardColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIStandardColor"]));
            }
            set {
                this["AOIStandardColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle AOIStandardStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["AOIStandardStyle"]));
            }
            set {
                this["AOIStandardStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float AOIStandardWidth {
            get {
                return ((float)(this["AOIStandardWidth"]));
            }
            set {
                this["AOIStandardWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 27.75pt")]
        public global::System.Drawing.Font AOIStandardFont {
            get {
                return ((global::System.Drawing.Font)(this["AOIStandardFont"]));
            }
            set {
                this["AOIStandardFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color AOIStandardFontColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIStandardFontColor"]));
            }
            set {
                this["AOIStandardFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color AOITargetFontColor {
            get {
                return ((global::System.Drawing.Color)(this["AOITargetFontColor"]));
            }
            set {
                this["AOITargetFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 27.75pt")]
        public global::System.Drawing.Font AOITargetFont {
            get {
                return ((global::System.Drawing.Font)(this["AOITargetFont"]));
            }
            set {
                this["AOITargetFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SteelBlue")]
        public global::System.Drawing.Color AOISearchRectFontColor {
            get {
                return ((global::System.Drawing.Color)(this["AOISearchRectFontColor"]));
            }
            set {
                this["AOISearchRectFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 27.75pt")]
        public global::System.Drawing.Font AOISearchRectFont {
            get {
                return ((global::System.Drawing.Font)(this["AOISearchRectFont"]));
            }
            set {
                this["AOISearchRectFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 27.75pt")]
        public global::System.Drawing.Font GazeFixationsFont {
            get {
                return ((global::System.Drawing.Font)(this["GazeFixationsFont"]));
            }
            set {
                this["GazeFixationsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color GazeFixationsFontColor {
            get {
                return ((global::System.Drawing.Color)(this["GazeFixationsFontColor"]));
            }
            set {
                this["GazeFixationsFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ReplayModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["ReplayModuleLocation"]));
            }
            set {
                this["ReplayModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point StatisticsModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["StatisticsModuleLocation"]));
            }
            set {
                this["StatisticsModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FixationsModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["FixationsModuleLocation"]));
            }
            set {
                this["FixationsModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DatabaseModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["DatabaseModuleLocation"]));
            }
            set {
                this["DatabaseModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AttentionMapModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["AttentionMapModuleLocation"]));
            }
            set {
                this["AttentionMapModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\DataSet\\OgamaDatabaseTe" +
            "mplate.mdf;Integrated Security=True;User Instance=False")]
        public string OgamaDatabaseTemplateConnectionString {
            get {
                return ((string)(this["OgamaDatabaseTemplateConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EyeTrackerSettingsPath {
            get {
                return ((string)(this["EyeTrackerSettingsPath"]));
            }
            set {
                this["EyeTrackerSettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color MouseFixationsFontColor {
            get {
                return ((global::System.Drawing.Color)(this["MouseFixationsFontColor"]));
            }
            set {
                this["MouseFixationsFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 27.75pt")]
        public global::System.Drawing.Font MouseFixationsFont {
            get {
                return ((global::System.Drawing.Font)(this["MouseFixationsFont"]));
            }
            set {
                this["MouseFixationsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float FIXMouseFixationsPenWidth {
            get {
                return ((float)(this["FIXMouseFixationsPenWidth"]));
            }
            set {
                this["FIXMouseFixationsPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle FIXMouseFixationsPenStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["FIXMouseFixationsPenStyle"]));
            }
            set {
                this["FIXMouseFixationsPenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 192")]
        public global::System.Drawing.Color FIXMouseFixationsPenColor {
            get {
                return ((global::System.Drawing.Color)(this["FIXMouseFixationsPenColor"]));
            }
            set {
                this["FIXMouseFixationsPenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color BackgroundColorForms {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColorForms"]));
            }
            set {
                this["BackgroundColorForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point FIXMouseToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["FIXMouseToolbarLocation"]));
            }
            set {
                this["FIXMouseToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("126, 25")]
        public global::System.Drawing.Point FIXGazeToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["FIXGazeToolbarLocation"]));
            }
            set {
                this["FIXGazeToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 25")]
        public global::System.Drawing.Point FIXOptionsToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["FIXOptionsToolbarLocation"]));
            }
            set {
                this["FIXOptionsToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point FIXTrialToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["FIXTrialToolbarLocation"]));
            }
            set {
                this["FIXTrialToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RPLTrialToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["RPLTrialToolbarLocation"]));
            }
            set {
                this["RPLTrialToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 27")]
        public global::System.Drawing.Point RPLGazeToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["RPLGazeToolbarLocation"]));
            }
            set {
                this["RPLGazeToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("415, 27")]
        public global::System.Drawing.Point RPLMouseToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["RPLMouseToolbarLocation"]));
            }
            set {
                this["RPLMouseToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("317, 25")]
        public global::System.Drawing.Point ATMCalculateToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["ATMCalculateToolbarLocation"]));
            }
            set {
                this["ATMCalculateToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point ATMTrialToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["ATMTrialToolbarLocation"]));
            }
            set {
                this["ATMTrialToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ogama.net/version.txt")]
        public string UpdateUri {
            get {
                return ((string)(this["UpdateUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ogama.net")]
        public string OgamaUri {
            get {
                return ((string)(this["OgamaUri"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point SCAStimuliToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SCAStimuliToolbarLocation"]));
            }
            set {
                this["SCAStimuliToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 25")]
        public global::System.Drawing.Point SCAGazeToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SCAGazeToolbarLocation"]));
            }
            set {
                this["SCAGazeToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 50")]
        public global::System.Drawing.Point SCAMouseToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SCAMouseToolbarLocation"]));
            }
            set {
                this["SCAMouseToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dots")]
        public string GazeFixationsDrawingMode {
            get {
                return ((string)(this["GazeFixationsDrawingMode"]));
            }
            set {
                this["GazeFixationsDrawingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string MouseFixationsDrawingMode {
            get {
                return ((string)(this["MouseFixationsDrawingMode"]));
            }
            set {
                this["MouseFixationsDrawingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeConnections {
            get {
                return ((bool)(this["GazeConnections"]));
            }
            set {
                this["GazeConnections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GazeNumbers {
            get {
                return ((bool)(this["GazeNumbers"]));
            }
            set {
                this["GazeNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MouseConnections {
            get {
                return ((bool)(this["MouseConnections"]));
            }
            set {
                this["MouseConnections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseNumbers {
            get {
                return ((bool)(this["MouseNumbers"]));
            }
            set {
                this["MouseNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 75")]
        public global::System.Drawing.Point SCALevenshteinToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SCALevenshteinToolbarLocation"]));
            }
            set {
                this["SCALevenshteinToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dot")]
        public global::System.Drawing.Drawing2D.DashStyle NoDataPenStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["NoDataPenStyle"]));
            }
            set {
                this["NoDataPenStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float NoDataPenSize {
            get {
                return ((float)(this["NoDataPenSize"]));
            }
            set {
                this["NoDataPenSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point AOIToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["AOIToolbarLocation"]));
            }
            set {
                this["AOIToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RecordingModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["RecordingModuleLocation"]));
            }
            set {
                this["RecordingModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SaliencyModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["SaliencyModuleLocation"]));
            }
            set {
                this["SaliencyModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ScanpathsModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["ScanpathsModuleLocation"]));
            }
            set {
                this["ScanpathsModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlidedesignModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["SlidedesignModuleLocation"]));
            }
            set {
                this["SlidedesignModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point SCRToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SCRToolbarLocation"]));
            }
            set {
                this["SCRToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point SALToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SALToolbarLocation"]));
            }
            set {
                this["SALToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 25")]
        public global::System.Drawing.Point SALGazeToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SALGazeToolbarLocation"]));
            }
            set {
                this["SALGazeToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 50")]
        public global::System.Drawing.Point SALCalculateToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["SALCalculateToolbarLocation"]));
            }
            set {
                this["SALCalculateToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5, 25")]
        public global::System.Drawing.Point RECToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["RECToolbarLocation"]));
            }
            set {
                this["RECToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point DTBToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["DTBToolbarLocation"]));
            }
            set {
                this["DTBToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SlideshowModuleLocation {
            get {
                return ((global::System.Drawing.Point)(this["SlideshowModuleLocation"]));
            }
            set {
                this["SlideshowModuleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string ActivatedHardwareTracker {
            get {
                return ((string)(this["ActivatedHardwareTracker"]));
            }
            set {
                this["ActivatedHardwareTracker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Secondary")]
        public string PresentationScreenMonitor {
            get {
                return ((string)(this["PresentationScreenMonitor"]));
            }
            set {
                this["PresentationScreenMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public string AOITargetTextAlignment {
            get {
                return ((string)(this["AOITargetTextAlignment"]));
            }
            set {
                this["AOITargetTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public string AOISearchRectTextAlignment {
            get {
                return ((string)(this["AOISearchRectTextAlignment"]));
            }
            set {
                this["AOISearchRectTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public string AOIDefaultTextAlignment {
            get {
                return ((string)(this["AOIDefaultTextAlignment"]));
            }
            set {
                this["AOIDefaultTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public string AOIBubbleTextAlignment {
            get {
                return ((string)(this["AOIBubbleTextAlignment"]));
            }
            set {
                this["AOIBubbleTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public string AOIArrowTextAlignment {
            get {
                return ((string)(this["AOIArrowTextAlignment"]));
            }
            set {
                this["AOIArrowTextAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color NoDataPenColor {
            get {
                return ((global::System.Drawing.Color)(this["NoDataPenColor"]));
            }
            set {
                this["NoDataPenColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color AOIBubbleColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIBubbleColor"]));
            }
            set {
                this["AOIBubbleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color AOIBubbleFontColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIBubbleFontColor"]));
            }
            set {
                this["AOIBubbleFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SandyBrown")]
        public global::System.Drawing.Color AOIArrowColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIArrowColor"]));
            }
            set {
                this["AOIArrowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color AOIArrowFontColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIArrowFontColor"]));
            }
            set {
                this["AOIArrowFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle AOIBubbleStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["AOIBubbleStyle"]));
            }
            set {
                this["AOIBubbleStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float AOIBubbleWidth {
            get {
                return ((float)(this["AOIBubbleWidth"]));
            }
            set {
                this["AOIBubbleWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana, 14.25pt, style=Bold")]
        public global::System.Drawing.Font AOIBubbleFont {
            get {
                return ((global::System.Drawing.Font)(this["AOIBubbleFont"]));
            }
            set {
                this["AOIBubbleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public global::System.Drawing.Drawing2D.DashStyle AOIArrowStyle {
            get {
                return ((global::System.Drawing.Drawing2D.DashStyle)(this["AOIArrowStyle"]));
            }
            set {
                this["AOIArrowStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float AOIArrowWidth {
            get {
                return ((float)(this["AOIArrowWidth"]));
            }
            set {
                this["AOIArrowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Verdana, 12pt")]
        public global::System.Drawing.Font AOIArrowFont {
            get {
                return ((global::System.Drawing.Font)(this["AOIArrowFont"]));
            }
            set {
                this["AOIArrowFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color AOIBubbleBrushColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIBubbleBrushColor"]));
            }
            set {
                this["AOIBubbleBrushColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color AOIArrowBrushColor {
            get {
                return ((global::System.Drawing.Color)(this["AOIArrowBrushColor"]));
            }
            set {
                this["AOIArrowBrushColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NameAndFill")]
        public string AOIBubbleDrawAction {
            get {
                return ((string)(this["AOIBubbleDrawAction"]));
            }
            set {
                this["AOIBubbleDrawAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NameEdgeFill")]
        public string AOIArrowDrawAction {
            get {
                return ((string)(this["AOIArrowDrawAction"]));
            }
            set {
                this["AOIArrowDrawAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaliencyCalculationPath {
            get {
                return ((string)(this["SaliencyCalculationPath"]));
            }
            set {
                this["SaliencyCalculationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogfilePath {
            get {
                return ((string)(this["LogfilePath"]));
            }
            set {
                this["LogfilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportSettingsPath {
            get {
                return ((string)(this["ImportSettingsPath"]));
            }
            set {
                this["ImportSettingsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OgamaScreenCaptureSettingsPath {
            get {
                return ((string)(this["OgamaScreenCaptureSettingsPath"]));
            }
            set {
                this["OgamaScreenCaptureSettingsPath"] = value;
            }
        }
    }
}
